local M = {
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Question = ' ',
    Info = ' ',
  },
  git = {
    add = '',
    Diff = '',
    Modified = '',
    Ignore = '',
    Rename = '',
    deleted = '',
    Repo = '',
  },
  ui = {
    BigCircle = ' ',
    BigUnfilledCircle = ' ',
    BookMark = ' ',
    Bug = ' ',
    Calendar = ' ',
    Check = ' ',
    ChevronRight = '>',
    Circle = ' ',
    Close = ' ',
    Code = ' ',
    Comment = ' ',
    Gear = ' ',
    History = ' ',
    Lightbulb = ' ',
    List = ' ',
    Lock = ' ',
    NewFile = ' ',
    Note = ' ',
    Package = ' ',
    Pencil = ' ',
    Project = ' ',
    Search = ' ',
    SignIn = ' ',
    Table = ' ',
    Telescope = ' ',
    extends = '❯',
    precedes = '❮',
  },
  misc = {
    expanded = ' ',
    collapsed = '󰁛 ',
    v_border = '▐',
  },
  mode = {
    c = '󰯱',
    i = '󰰃',
    n = '󰰒',
    r = '󰰞',
    s = '󰰡',
    t = '󰰤',
    v = '󰰪',
  },
}

return M

